[project]
name = "langgraph-multi-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langgraph>=0.2.69",
]

[dependency-groups]
dev = [
    "ruff>=0.9.4",
]
